# Generated by Django 2.2.16 on 2020-10-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20201005_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updeate_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('desc', models.CharField(max_length=256, verbose_name='商品简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='商品价格')),
                ('image', models.ImageField(upload_to='goods', verbose_name='商品图片')),
                ('menu', models.ManyToManyField(blank=True, to='goods.GoodsTypeMenu', verbose_name='拥有的所有种类')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
