# Generated by Django 2.2.16 on 2020-10-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20201006_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='component',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='组件名称'),
        ),
        migrations.AddField(
            model_name='goodstypemenu',
            name='component',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='组件名称'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='url',
            field=models.CharField(max_length=128, verbose_name='URL'),
        ),
    ]
