# Generated by Django 2.2.16 on 2020-10-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='一级菜单名称')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='图标')),
                ('url', models.CharField(max_length=128, verbose_name='URL')),
                ('component', models.CharField(max_length=20, verbose_name='组件名称')),
            ],
            options={
                'verbose_name': '一级菜单',
                'verbose_name_plural': '一级菜单',
                'db_table': 'drf_menu',
            },
        ),
        migrations.CreateModel(
            name='MenuTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
                ('url', models.CharField(max_length=128, verbose_name='URL')),
                ('component', models.CharField(blank=True, max_length=20, null=True, verbose_name='组件名称')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu', verbose_name='所属菜单')),
            ],
            options={
                'verbose_name': '二级菜单',
                'verbose_name_plural': '二级菜单',
                'db_table': 'drf_menu_type',
            },
        ),
        migrations.CreateModel(
            name='MenuTypeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=20, verbose_name='标识图')),
                ('name', models.CharField(max_length=20, verbose_name='种类名称')),
                ('url', models.CharField(max_length=128, verbose_name='URL')),
                ('component', models.CharField(blank=True, max_length=20, null=True, verbose_name='组件名称')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.MenuTypes', verbose_name='所属二级菜单')),
            ],
            options={
                'verbose_name': '三级菜单',
                'verbose_name_plural': '三级菜单',
                'db_table': 'drf_menu_type_item',
            },
        ),
    ]
