# Generated by Django 2.2.16 on 2020-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutypeitem',
            name='image',
            field=models.CharField(max_length=128, verbose_name='标识图'),
        ),
    ]
